### ISSUE TITLE
Documentation is missing option information

### ISSUE THREAD

**Issue by arjunmehta** [timoxley/columnify#18]
Hi there!

Just noticed that the documentation seems to be missing descriptions of most [API options](https://github.com/timoxley/columnify/blob/master/index.js#L20-L30).

For example, the readme talks about [maximum and minimum widths](https://github.com/timoxley/columnify#wrapping-column-cells), but there is no evidence of the API to do that in the example provided. Perhaps it got deleted?

Am I missing something?

**Comment by danyshaanan** [comment]
maxWidth and minWidth are covered under "Wrapping Column Cells". It might look less trivial as it is used per specific column, but I don't think it would be good to add a specific example to every case. Maybe we should add a note about "global" configurations vs "per column" ones.

I've added documentations for `showHeaders`: 9c04f8b7a821a7689eafad92fd7cbf3875de6c4e

If I'm not mistaken, the only ones left are `headingTransform` and `dataTransform`. @arjunmehta - Care to give it a shot?

**Comment by arjunmehta** [comment]
Sure @danyshaanan I'll give it a go closer to the end of the day, or early tomorrow!

I'll do `headingTransform` and `dataTransform`. Still not really finding `maxWidth` and `minWidth` explained well in the docs, so I'll take a shot at that too.

**Comment by timoxley** [comment]
Whoo great thanks.
