### ISSUE TITLE
Suggestion: allow headingTransform to be defined for all headings

### ISSUE THREAD

**Issue by tdmalone** [timoxley/columnify#48]
Thank you for the excellent and flexible module! Loving how easy it makes it.

A suggestion: would it be possible to apply a `headingTransform` property, defined at the top level of the config, to _all_ headings? This would make it easy to eg. apply string transformations, regexes etc. to every heading rather than having to do it seperately for each one.

**Comment by tdmalone** [comment]
Oops, I do apologise, this is already possible, I just got confused by the documentation. Have submitted PR.

**Comment by danyshaanan** [comment]
No worried!
