### ISSUE TITLE
Non-printing terminal control characters influence layout

### ISSUE THREAD

**Issue by Trial-In-Error** [timoxley/columnify#57]
I'm hoping to use [terminal-link](https://github.com/sindresorhus/terminal-link) to generate links in one column of a columnify layout. However, it appears that the column width is calculated including these control / escaped characters. Unfortunately, I can't find a work-around either; for my use case, I'd be happy to set minWidth, maxWidth, and truncate dynamically to the "printable" length of the longest line, but this doesn't appear to work (the output is exactly the same as with those values not set).

**Comment by danyshaanan** [comment]
Can you give an example in code/output of what you're trying to do? I could look into it if I'll have the code to reproduce the problem.

**Comment by Trial-In-Error** [comment]
Sure! Take a look at [this repo](https://github.com/Trial-In-Error/columnify-test-repro). You'll need a terminal that supports link embedding (I'm using iTerm 2); [this gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) has a test-case for that.

Given that your terminal supports link embedding, clone the `columnify-test-repro`, run `node index.js`, and note the difference in the table layouts.

**Comment by danyshaanan** [comment]
Related to open issues https://github.com/timoxley/columnify/issues/17 and https://github.com/timoxley/columnify/issues/26, and might be solved with [sindresorhus/cli-truncate](https://github.com/sindresorhus/cli-truncate). @timoxley - would it make sense to use cli-truncate inside [truncateString](https://github.com/timoxley/columnify/blob/master/utils.js#L163)? If so, I'll give it a shot.
